name: perfect_freehand_example
version: 1.0.0
description: Draw perfect pressure-sensitive freehand lines. Flutter example.
homepage: https://github.com/steveruizok/perfect-freehand-dart
repository: https://github.com/steveruizok/perfect-freehand-dart
documentation: https://github.com/steveruizok/perfect-freehand-dart
issue_tracker: https://github.com/steveruizok/perfect-freehand-dart/issues
publish_to: "none"

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  file_saver: ^0.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  google_fonts: ^8.0.0
  perfect_freehand:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
